routes/admin.php
<?php

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    Route::get('/posts/create', 'Admin\PostController@create')->name('voyager.posts.create');
    Route::post('/posts', 'Admin\PostController@store')->name('voyager.posts.store');
    Route::get('/posts/{post}/edit', 'Admin\PostController@edit')->name('voyager.posts.edit');
    Route::put('/posts/{post}', 'Admin\PostController@update')->name('voyager.posts.update');
    Route::post('/categories', 'Admin\CategoriesController@store')->name('voyager.categories.store');
    Route::put('/categories/{category}', 'Admin\CategoriesController@update')->name('voyager.categories.update');
    Route::get('/categories/create', 'Admin\CategoriesController@create')->name('voyager.categories.create');
    Route::get('/categories/{category}/edit', 'Admin\CategoriesController@edit')->name('voyager.categories.edit');
    Route::get('/categories-list/{id?}', 'Admin\CategoriesController@index')->name('voyager.categories.index');
    Route::get('/translates', 'Admin\TranslateController@index')->name('lang.file.index');
    Route::get('/translates/edit-lang-file/{cryptFileName}', 'Admin\TranslateController@editLangFile')->name('lang.file.form');
    Route::put('/translates/update-lang-file/{cryptFileName}', 'Admin\TranslateController@updateLangFile')->name('lang.file.update');
    Route::post('/translates/add-keys-to-lang-files/{cryptFileName}', 'Admin\TranslateController@addKeysToLangFiles')->name('lang.file.add.keys');
    Route::get('/translates/upgrade-lang-file/', 'Admin\TranslateController@upgradeLangFiles')->name('lang.file.upgrade');
    Route::get('/translates/export-to-db/', 'Admin\TranslateController@exportToDb')->name('lang.file.export-to-db');
    Route::get('/translates/update-db/', 'Admin\TranslateController@updateTranslationInDb')->name('lang.file.update-db');
    Route::get('/translates/import-from-db/', 'Admin\TranslateController@importFromDb')->name('lang.file.import-from-db');
});

app/Models/Post/Category.php
<?php

namespace App\Models\Post;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use TCG\Voyager\Traits\HasRelationships;
use TCG\Voyager\Traits\Translatable;

/**
 * Category model.
 */
class Category extends Model
{
    use Translatable,
        HasRelationships;

    protected $translatable = ['name'];

    protected $table = 'categories';

    protected $fillable = ['slug', 'name'];

    /**
     * Id knowledge category.
     *
     * @var int
     */
    const CATEGORY_KNOWLEDGE_ID = 1;

    /**
     * Id news category.
     *
     * @var int
     */
    const CATEGORY_NEWS_ID = 2;

    /**
     * Get list post from category.
     */
    public function posts()
    {
        return $this->hasMany('App\Models\Post\Post');
    }

    public function children()
    {
        return $this->hasMany('App\Models\Post\Category', 'parent_id', 'id');
    }

    public function parentId()
    {
        return $this->belongsTo(self::class);
    }

    /**
     * Get children categories by id parent category.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query {@inheritdoc}
     * @param int $id
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeChildrenCategoriesById(Builder $query, $id)
    {
        return $query->where('parent_id', $id);
    }
}

app/Models/Post/Post.php
<?php

namespace App\Models\Post;

use Illuminate\Database\Eloquent\Builder;
use App\Models\Post\Category;
use TCG\Voyager\Models\Post as VoyagerPost;
use TCG\Voyager\Traits\HasRelationships;
use TCG\Voyager\Traits\Resizable;
use TCG\Voyager\Traits\Translatable;

/**
 * Post model.
 */
class Post extends VoyagerPost
{
    use Translatable,
        Resizable,
        HasRelationships;

    protected $translatable = ['title', 'seo_title', 'excerpt', 'body', 'meta_description', 'meta_keywords'];

    /**
     * Post status published.
     *
     * @var string
     */
    const STATUS_PUBLISHED = 'PUBLISHED';

    /**
     * Post status draft.
     *
     * @var string
     */
    const STATUS_DRAFT = 'DRAFT';

    /**
     * Post status pending.
     *
     * @var string
     */
    const STATUS_PENDING = 'PENDING';

    /**
     * Count last news in block <Last news>.
     *
     * @var int
     */
    const LIMIT_LAST_NEWS = 2;

    /**
     * Scope published posts.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePublished(Builder $query)
    {
        return $query->where('status', self::STATUS_PUBLISHED);
    }

    /**
     * Scope posts in category news.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeNews(Builder $query)
    {
        $categoriesNewsIds = Category::childrenCategoriesById(Category::CATEGORY_NEWS_ID)->pluck('id');

        return $query->whereIn('category_id', $categoriesNewsIds)
            ->orWhere('category_id', Category::CATEGORY_NEWS_ID);
    }

    /**
     * Scope posts in category knowledge.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeKnowledge(Builder $query)
    {
        $categoriesKnowledgeIds = Category::childrenCategoriesById(Category::CATEGORY_KNOWLEDGE_ID)->pluck('id');

        return $query->whereIn('category_id', $categoriesKnowledgeIds)
            ->orWhere('category_id', Category::CATEGORY_KNOWLEDGE_ID);
    }

    /**
     * Scope posts by category.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeByCategory(Builder $query, $categoryId)
    {
        return $query->where('category_id', $categoryId);
    }

    /**
     * Scope posts by tag.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeByTag(Builder $query, $tagName)
    {
        return $query->where('tags', 'like', $tagName)
            ->orWhere('tags', 'like', $tagName . ',%')
            ->orWhere('tags', 'like', '%,'. $tagName)
            ->orWhere('tags', 'like', '%,'. $tagName . ',%');
    }

    /**
     * Relation with category.
     *
     */
    public function category()
    {
        return $this->hasOne(Category::class, 'id', 'category_id');
    }

    public function getListTagsAttribute()
    {
        if (!empty($this->tags)) {
            return explode(',', $this->tags);
        }

        return [];
    }

    public function getIsBelongsRootCategoryAttribute()
    {
        return in_array($this->category_id, [Category::CATEGORY_NEWS_ID, Category::CATEGORY_KNOWLEDGE_ID]);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use TCG\Voyager\Http\Controllers\VoyagerBaseController;
use Illuminate\Http\Request;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Events\BreadDataUpdated;
use App\Models\Post\Post;
use TCG\Voyager\Events\BreadDataAdded;

class PostController extends VoyagerBaseController
{
    //***************************************
    //
    //                   /\
    //                  /  \
    //                 / /\ \
    //                / ____ \
    //               /_/    \_\
    //
    //
    // Add a new item of our Data Type BRE(A)D
    //
    //****************************************

    public function create(Request $request)
    {
        $slug = $this->getSlug($request);

        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        // Check permission
        //$this->authorize('add', app($dataType->model_name));

        $dataTypeContent = new Post();

        foreach ($dataType->addRows as $key => $row) {
            $details = json_decode($row->details);
            $dataType->addRows[$key]['col_width'] = isset($details->width) ? $details->width : 100;
        }

        // If a column has a relationship associated with it, we do not want to show that field
        $this->removeRelationshipField($dataType, 'add');

        // Check if BREAD is Translatable
        $isModelTranslatable = is_bread_translatable($dataTypeContent);

        $view = 'voyager::bread.edit-add';

        if (view()->exists("voyager::$slug.edit-add")) {
            $view = "voyager::$slug.edit-add";
        }

        return Voyager::view($view, compact('dataType', 'dataTypeContent', 'isModelTranslatable'));
    }

    /**
     * POST BRE(A)D - Store data.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $slug = $this->getSlug($request);

        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        // Check permission
        $this->authorize('add', app($dataType->model_name));

        $tags = $request->get('tags', []);

        if (!empty($tags)) {
            $request[ 'tags' ] = implode(',', $tags);
        } else {
            $request[ 'tags' ] = null;
        }

        // Validate fields with ajax
        $val = $this->validateBread($request->all(), $dataType->addRows);

        if ($val->fails()) {
            return response()->json(['errors' => $val->messages()]);
        }

        if (!$request->has('_validate')) {
            $data = $this->insertUpdateData($request, $slug, $dataType->addRows, new Post());

            event(new BreadDataAdded($dataType, $data));

            if ($request->ajax()) {
                return response()->json(['success' => true, 'data' => $data]);
            }

            if ($request->featured === 'on' && $request->attach === 'on') {
                Post::where('id', '<>', $data->id)->update(['featured' => 0]);
            }

            return redirect()
                ->route("voyager.{$dataType->slug}.index")
                ->with([
                        'message'    => __('voyager::generic.successfully_added_new')." {$dataType->display_name_singular}",
                        'alert-type' => 'success',
                    ]);
        }
    }

    //***************************************
    //                ______
    //               |  ____|
    //               | |__
    //               |  __|
    //               | |____
    //               |______|
    //
    //  Edit an item of our Data Type BR(E)AD
    //
    //****************************************

    public function edit(Request $request, $id)
    {
        $slug = $this->getSlug($request);

        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        $relationships = $this->getRelationships($dataType);

        $dataTypeContent = Post::where('id', $id)
            ->with($relationships)
            ->firstOrFail();

        foreach ($dataType->editRows as $key => $row) {
            $details = json_decode($row->details);
            $dataType->editRows[$key]['col_width'] = isset($details->width) ? $details->width : 100;
        }

        // If a column has a relationship associated with it, we do not want to show that field
        $this->removeRelationshipField($dataType, 'edit');

        // Check permission
        //$this->authorize('edit', $dataTypeContent);

        // Check if BREAD is Translatable
        $isModelTranslatable = is_bread_translatable($dataTypeContent);

        $view = 'voyager::bread.edit-add';

        if (view()->exists("voyager::$slug.edit-add")) {
            $view = "voyager::$slug.edit-add";
        }

        return Voyager::view($view, compact('dataType', 'dataTypeContent', 'isModelTranslatable'));
    }

    // POST BR(E)AD
    public function update(Request $request, $id)
    {
        $slug = $this->getSlug($request);

        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        // Compatibility with Model binding.
        $id = $id instanceof Model ? $id->{$id->getKeyName()} : $id;

        $data = Post::where('id', $id)->firstOrFail();

        // Check permission
        //$this->authorize('edit', $data);

        $tags = $request->get('tags', []);

        if (!empty($tags)) {
            $request[ 'tags' ] = implode(',', $tags);
        } else {
            $request[ 'tags' ] = null;
        }

        // Validate fields with ajax
        $val = $this->validateBread($request->all(), $dataType->editRows, $dataType->name, $id);

        if ($val->fails()) {
            return response()->json(['errors' => $val->messages()]);
        }

        if (!$request->ajax()) {
            $this->insertUpdateData($request, $slug, $dataType->editRows, $data);

            event(new BreadDataUpdated($dataType, $data));

            if ($request->featured === 'on' && $request->attach === 'on') {
                Post::where('id', '<>', $id)->update(['featured' => 0]);
            }

            return redirect()
                ->route("voyager.{$dataType->slug}.index")
                ->with([
                    'message'    => __('voyager::generic.successfully_updated')." {$dataType->display_name_singular}",
                    'alert-type' => 'success',
                ]);
        }
    }
}

app/Http/Controllers/Post/PostController.php
<?php

namespace App\Http\Controllers\Post;

use App\Models\Post\Post;
use App\Models\Post\Category;
use App\Http\Controllers\Controller as BaseController;

/**
 * Controller for posts.
 */
class PostController extends BaseController
{
    /**
     * Display page posts.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $posts = Post::news()
            ->published()
            ->paginate();

        return view('post.index', compact('posts'));
    }

    /**
     * Display page some posts.
     *
     * @param int $id Post id
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $post = Post::where('id', $id)
            ->published()
            ->firstOrFail();

        $lastPosts = Post::published()
            ->where('id', '<>', $id)
            ->orderBy('created_at', 'desc')
            ->limit(Post::LIMIT_LAST_NEWS)
            ->get();

        $dayNews = Post::where('featured',  1)
            ->published()
            ->orderBy('created_at', 'desc')
            ->get();

        return view('post.show', compact('post', 'lastPosts', 'dayNews'));
    }

    /**
     * Display posts by category.
     *
     * @param \App\Models\Post\Category $category Category model
     * @return \Illuminate\View\View
     */
    public function byCategory(Category $category)
    {
        if ($category->parent_id != Category::CATEGORY_NEWS_ID) {
            abort(404);
        }

        $posts = Post::published()
            ->byCategory($category->id)
            ->paginate();

        return view('post.index', compact('posts'));
    }

    /**
     * Display posts by tag.
     *
     * @param string $tagName Tag name
     * @return \Illuminate\View\View
     */
    public function byTag($tagName)
    {
        $posts = Post::news()
            ->byTag($tagName)
            ->published()
            ->paginate();

        return view('post.index', compact('posts'));
    }
}

resources/views/post/index.blade.php
@extends('layouts.external')

@section('css')
<link rel="stylesheet" href="/post/css/uber-icons.css">
<link rel="stylesheet" href="/post/css/refresh.css">
<link rel="stylesheet" href="/post/css/main-2ebd3f14a4_news.css">
@endsection

@section('title')
Посты
@endsection


@section('content')

<div class="news">
    <div class="news_conteiner">
        <div class="wrapper">
            <div class="left_block f_left">

                @widget('Banners', ['uri' => ['banner1', 'banner2']])

            </div>
            <div class="center_block f_left">

                @foreach ($posts as $post)

                    <div class="news_block">
                        <div class="img">

                            @if ($post->image)

                                <div class="singleImageContainerExternal" style="background-image: url('{{ URL::asset('storage/' . $post->image) }}');"></div>

                            @else

                                <div class="singleImageContainerExternal" style="background-image: url();"></div>

                            @endif

                            <h3><a href="{{ route('news.show', ['id' => $post->id]) }}">{{ $post->title }}</a></h3>
                        </div>
                        <div class="short_content">
                            <p>{{ $post->excerpt }}</p>
                        </div>
                        <div class="footer_news">
                            <div class="data f_left">{{ \Carbon\Carbon::parse($post->created_at)->format('d.m.Y') }}</div>
                            <div class="developments f_left">

                                @if ($post->category && !$post->is_belongs_root_category )

                                    <a href="{{ route('news.category', ['category' => $post->category]) }}" rel="category">{{ $post->category->name }}</a>

                                @endif

                            </div>
                            <div>
                                Tags:

                                @foreach ($post->listTags as $tag)

                                    <a href="{{ route('news.tag', ['tagName' => $tag]) }}">{{ $tag }}</a>

                                    @if (!$loop->last)
                                        |
                                    @endif

                                @endforeach

                            </div>
                            <div class="share f_right"><a href="" class="block transition">Поделиться</a></div>
                            <div class="clear"></div>
                        </div>
                    </div>

                @endforeach

                {{ $posts->links() }}

            </div>
            <div class="right_block f_right">

                @widget('Banners', ['uri' => ['right-block']])

            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

@endsection

resources/views/post/show.blade.php
@extends('layouts.external')

@section('css')
<link rel="stylesheet" href="/post/css/uber-icons.css">
<link rel="stylesheet" href="/post/css/refresh.css">
<link rel="stylesheet" href="/post/css/main-2ebd3f14a4_news.css">
@endsection

@section('title')
Посты
@endsection


@section('content')

<div class="news">
    <div class="open_news_conteiner">
        <div class="wrapper">

            <div class="left_block f_left">
                <div class="open_news">
                    <h3>{{ $post->title }}</h3>

                    @if ($post->image)

                          <!--<img src="{{ URL::asset('storage/' . $post->image) }}">-->

                    @endif

                    <div class="footer_img">
                        <div class="data f_left">{{ \Carbon\Carbon::parse($post->created_at)->format('d.m.Y')}}</div>
                        <div class="developments f_left">

                            @if ($post->category && !$post->is_belongs_root_category)

                                <a href="{{ route('news.category', ['category' => $post->category]) }}" rel="category">{{ $post->category->name }}</a>

                            @endif

                        </div>
                        <div class="share f_right"><a href="" class="block transition">Поделиться</a></div>
                        <div class="clear"></div>

                        @if ($post->image)

                            <div class="singleImageContainer" style="background-image: url({{ URL::asset('storage/' . $post->image) }});"></div>

                        @endif

                        <p>{!! $post->body !!}</p>

                        <div>
                            Tags:

                            @foreach ($post->listTags as $tag)

                                <a href="{{ route('news.tag', ['tagName' => $tag]) }}">{{ $tag }}</a>

                                @if (!$loop->last)
                                    |
                                @endif

                            @endforeach

                        </div>
                    </div>
                </div>
            </div>
            <div class="right_block f_right">
                <a href="#" class="block transition join_us">НАЧАТЬ СОТРУДНИЧЕСТВО</a>

                @if ($dayNews->count())

                    <h4>Новости дня</h4>
                    <div class="right_news">
                        <div id="newofday_widget-2" class="widget widget_newofday_widget">

                            @foreach ($dayNews as $news)

                                <div class="right_news">
                                    <img src="">
                                    <div class="data">{{ \Carbon\Carbon::parse($news->created_at)->format('d.m.Y')}}</div>
                                    <h3>{{ $news->title }}</h3>
                                    <p>{{ str_limit($news->excerpt, $limit = 150, $end = '...') }}</p>
                                    <a href="{{ route('news.show', ['id' => $news->id]) }}" class="block transition learn_more">Читать далее...</a>
                                </div>

                            @endforeach

                        </div>
                    </div>

                @endif
                @if ($lastPosts->count())

                    <h4>Последние</h4>
                    <div class="right_news_last">
                        <div id="lastnews_widget-2" class="widget widget_lastnews_widget">
                            <div class="right_news_last">

                                @foreach ($lastPosts as $post)

                                    <div class="data">{{ \Carbon\Carbon::parse($post->created_at)->format('d.m.Y')}}</div>
                                    <h3>{{ $post->title }}</h3>
                                    <p>{{ str_limit($post->excerpt, $limit = 150, $end = '...') }}</p>
                                    <a href="{{ route('news.show', ['id' => $post->id]) }}" class="block transition learn_more">Читать далее...</a>

                                @endforeach

                            </div>
                        </div>
                    </div>

                @endif

            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

@endsection

@section('javascript')
@endsection